# Generated by Django 3.2.5 on 2022-04-13 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Article',
            new_name='Vault',
        ),
    ]
