# Generated by Django 3.2.5 on 2022-04-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_rename_article_vault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='url',
            field=models.URLField(blank=True, default='www.facebook.com', max_length=255),
            preserve_default=False,
        ),
    ]
