# Generated by Django 3.2.5 on 2022-04-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0003_alter_vault_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vault',
            name='url',
        ),
        migrations.AddField(
            model_name='vault',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
