# Generated by Django 3.2.5 on 2022-04-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0004_auto_20220426_0634'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='url',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
