# Generated by Django 3.2.5 on 2022-04-26 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0005_vault_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='url',
            field=models.URLField(blank=True, max_length=255, validators=[django.core.validators.URLValidator]),
        ),
    ]
