# Generated by Django 3.2.5 on 2022-05-18 06:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0009_alter_vault_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
