# Generated by Django 4.0.3 on 2022-06-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0013_alter_vault_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
