# Generated by Django 4.0.3 on 2022-06-27 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0014_alter_vault_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vault',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
