# Generated by Django 4.0.3 on 2022-06-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_alter_vault_password_alter_vault_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='username',
            field=models.CharField(max_length=10),
        ),
    ]
