# Generated by Django 4.0.3 on 2022-06-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0015_alter_vault_password_alter_vault_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=models.BinaryField(max_length=100),
        ),
    ]
