# Generated by Django 4.0.3 on 2022-06-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0016_alter_vault_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
