# Generated by Django 3.2.5 on 2022-06-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0018_alter_vault_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=models.BinaryField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vault',
            name='username',
            field=models.BinaryField(max_length=100),
        ),
    ]
