# Generated by Django 3.2.5 on 2022-06-29 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0019_auto_20220629_0526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vault',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
