# Generated by Django 3.2.5 on 2022-06-29 07:22

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0020_auto_20220629_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vault',
            name='password',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='vault',
            name='username',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
    ]
